// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/polarsource/polar-go/models/components"
)

type EventTypesUpdateEventTypeRequest struct {
	// The event type ID.
	ID              string                     `pathParam:"style=simple,explode=false,name=id"`
	EventTypeUpdate components.EventTypeUpdate `request:"mediaType=application/json"`
}

func (e *EventTypesUpdateEventTypeRequest) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EventTypesUpdateEventTypeRequest) GetEventTypeUpdate() components.EventTypeUpdate {
	if e == nil {
		return components.EventTypeUpdate{}
	}
	return e.EventTypeUpdate
}

type EventTypesUpdateEventTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	EventType *components.EventType
}

func (e *EventTypesUpdateEventTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EventTypesUpdateEventTypeResponse) GetEventType() *components.EventType {
	if e == nil {
		return nil
	}
	return e.EventType
}
