// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EventTypeUpdate struct {
	// The label for the event type.
	Label string `json:"label"`
}

func (e *EventTypeUpdate) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}
